language: node_js
sudo: false
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10

os:
  - linux
  - osx
script:
  - npm test
  - npm run check-node-support
after_success:
  - npm run codecov -- -f coverage/lcov.info

notifications:
  email: false
