language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

os:
  - linux
  - osx
script:
  - npm test
after_success:
  - npm run codecov -- -f coverage/lcov.info

notifications:
  email: false
